### ISSUE TITLE
transformations of fixation maps and discrete maps

### ISSUE THREAD

**Issue by DilaraAlbayrak** [CZHQuality/Sal-CFS-GAN#6]
Hi,

I see that in table 1 of the paper, it is clearly stated image transformation generation codes. I just want to make sure that whether these transformations are applied to the fixation maps and discrete maps as well as RGB images. Let's take in hand Mirroring, I will share the original and mirrored RGB image and corresponding fixation map, below, I see that, while RGB images are a mirror pair, the fixation maps are not. Maybe you mirror the discrete maps, then recreate continuous fixation maps and the difference appears while recreating, though I am not sure.  Am I missing some point? Thanks in advance.
![samples](https://user-images.githubusercontent.com/7215154/75099501-6d64bb80-55d3-11ea-8aaa-1a6784487f00.png)

**Comment by DilaraAlbayrak** [comment]
I miss the point that you have also show participants the transformed stimuli and new fixation points appeared like that. I have a dataset in which I don't have collected data for transformed images, I have regular RGB frames and fixation points of the frames, then should I use your work without image transformations?

**Comment by CZHQuality** [comment]
Hi,

I do the same transformation to the "RGB image", "Fixation map", and the "Discrete fixation map" simultaneously, to make sure the transformed versions are still align with each other point-to-point.

Our method supports regular dataset without the transformed versions. 

Notice that you should pre-train the model on the large-scale dataset such as SALICON, then fine-tune it on your own dataset. Otherwise, training the model on your own dataset directly will result in over-fitting.

**Comment by DilaraAlbayrak** [comment]
Thanks for the answer, I still don't understand the difference between corresponding fixation maps for the mirror pair. When I read the paper, I understand that the participants are exposed to both the original RGB and its mirrored version and fixations are collected separately, so it is normal that there is a difference between fixation maps of mirrored images, but I am not quite sure of that.

**Comment by CZHQuality** [comment]
Hi,

Sorry for the unclear explanation. 

As shown in the figures your provided, the fixation maps are collected seperately, because we present the original RGB imag and the mirrored image to the observes seperately, in order to see what's the impact of mirroring transformation on the subjective human attention.

What I mentioned in the previous answer "I do the same transformation to the "RGB image", "Fixation map", and the "Discrete fixation map" simultaneously, to make sure the transformed versions are still align with each other point-to-point", 
this operation is used for quantifying the difference between the human attention on orignal image and the mirrored version, because we have to align the human fixation maps point-to-point, otherwise we can not compute some point-wise metrics (such as MSE or CC).

Your understanding is RIGHT. We collect the fixation maps seperately, so there will be some slight differences. At the same time, that's one main goal of this paper: to explore the impact of transformations to human attention.

Thank you very much !!

**Comment by DilaraAlbayrak** [comment]
Thank you for the source and your explanation :)
